version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arkan-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/ai_bot"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ai_bot
      MARIADB_USER: nestuser
      MARIADB_PASSWORD: nestpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
